public class Main {
    public static void main(String[] args) {
        System.out.println("Первое задание!");
int varByte=100;
System.out.println("Значение переменной varByte"+" c типом  byte="+ varByte);
short varShort=1000;
System.out.println("Значение переменной varShort"+" c типом  short="+ varShort);
int  varInt=1987654321;
System.out.println("Значение переменной varInt"+" c типом  int="+ varInt);
long varLong;
varLong=12345678987654321L;
System.out.println("Значение переменной varLong"+" c типом  long="+ varLong);
float varFloat;
varFloat=123.321F;
System.out.println("Значение переменной varFloat"+" c типом  float="+ varFloat);
 double varDouble;
 varDouble=321.12345678;
 System.out.println("Значение переменной varDouble"+" c типом  double=" + varDouble);
        System.out.println("Второе задание!");
        byte b=67;
        short s=-159;
        short s1=569;
        int i=27897;
        long l=987_678_965_549L;
        float f=27.12f;
        double d=2.786;
        System.out.println("Третье задание!");
        short totalPaper=480;
        byte countPupil1=23;
        byte countPupil2=27;
        byte countPupil3=30;
        int quanOnOnePupil=totalPaper/(countPupil1+countPupil2+countPupil3);
        System.out.println("На каждого ученика рассчитано " +quanOnOnePupil +" листов бумаги");
        System.out.println("Четвёртое  задание!");
       byte prodBottle1=16/2;
       int prodBottle20=prodBottle1*20;
       int prodBottleDay=prodBottle1*60*24;
       int prodBottle3Day=prodBottleDay*3;
       int prodBottleMonth=prodBottleDay*30;
        System.out.println("за 20 минут машина произвела "+  prodBottle20 +" штук бутылок");
        System.out.println(" В сутки  машина производит  "+  prodBottleDay +" штук бутылок");
        System.out.println("За три дня   машина производит  "+  prodBottle3Day +" штук бутылок");
        System.out.println("За месяц   машина производит  "+  prodBottleMonth +" штук бутылок");
        System.out.println("Пятое   задание!");
       short  totalCountJar=120;
       byte expendClassWhite=2;
        byte expendClassBrown=4;
       int totalClass=totalCountJar/(expendClassWhite+expendClassBrown);
       int  countWhitePaint=totalClass*expendClassWhite;
      int  countBrownPaint=totalClass*expendClassBrown;
        System.out.println("В школе, где " + totalClass +" классов, нужно "+countWhitePaint +  " банок белой краски и");
        System.out.println( countBrownPaint +  " банок коричневой  краски.");
        System.out.println("Шестое    задание!");
        byte countBanana=5;
        byte weigthOneBanana=80;
        short  volumeMilk=200;
        byte weigthMilk100g=105;
        byte countIceCream=2;
        byte weigthOneBriket=100;
        byte countEgg=4;
        byte weigthOneEgg=70;
        int totalGr=countBanana*weigthOneBanana+volumeMilk/100*weigthMilk100g+countIceCream*weigthOneBriket;
        totalGr=totalGr+countEgg*weigthOneEgg;
         float totalKg=totalGr/1000f;
        System.out.println("Количество такого спортзавтрака составляет:"+ totalGr + " граммов");
        System.out.println("или "+ totalKg+ " кг");
        System.out.println("Седьмое  задание");
        int weigth=7;
        short lostWiegthDayGr1=250;
        short lostWiegthDayGr2=500;
        float countDay1=weigth*1000/lostWiegthDayGr1;
        float countDay2=weigth*1000/lostWiegthDayGr2;
        System.out.println("Для того чтобы спортсмену сбросить "+weigth +" кг при похудении " +lostWiegthDayGr1+" в день" );
        System.out.println("Потребуется в среднем "+ countDay1 +" дней");
        System.out.println("Для того чтобы спортсмену сбросить "+weigth +" кг при похудении " +lostWiegthDayGr2+" в день" );
        System.out.println("Потребуется в среднем "+ countDay2 +" дней");
        System.out.println("Восьмое   задание");
        int payMashaMonth=67_760;
        int payDenisMonth=83_690;
        int payKristinaMonth=76_230;
        int newPayMashaYear=payMashaMonth*12 + payMashaMonth/10*12;
        int newPayDenisYear=payDenisMonth*12  + payDenisMonth/10*12;
        int newPayKristinaYear=payKristinaMonth*12 + payKristinaMonth/10*12;
        System.out.println("Маша теперь получает в месяц  "+(payMashaMonth+payMashaMonth/10) +" рублей");
        System.out.println("Годовой доход вырос на "+(newPayMashaYear-payMashaMonth*12)+" рублей");
        System.out.println("Денис теперь получает в месяц  "+(payDenisMonth+payDenisMonth/10) +" рублей");
        System.out.println("Годовой доход вырос на "+(newPayDenisYear-payDenisMonth*12)+" рублей");
        System.out.println("Кристина теперь получает в месяц  "+(payKristinaMonth+payKristinaMonth/10) +" рублей");
        System.out.println("Годовой доход вырос на "+(newPayKristinaYear-payKristinaMonth*12)+" рублей");
    }
}